### ISSUE TITLE
when accessing endpoint /v1/catalog/service/my-service returning empty [] result

### ISSUE THREAD

**Issue by aspiringpawan** [twinformatics/eureka-consul-adapter#19]
Hello,

I am using eureka-consul-adapter version 1.0.0 and facing issue while accessing endpoint "/v1/catalog/service/my-service" returning empty[] as response.
Using Spring boot 2.0.6 and Spring cloud version Finchley.Release.

**Comment by tine2k** [comment]
Do you see your service in `/v1/catalog/services`?

**Comment by aspiringpawan** [comment]
Yes. All registered services in eureka is showing but response is like :{"API-GATEWAY":[],"CONFIG-SERVER":[]}.
Apart from adding dependency for eureka-consul-adapter . is there any configuration property required to be added ?

**Comment by tine2k** [comment]
try `/v1/catalog/service/API-GATEWAY`. the service name is case-sensitive.

**Comment by aspiringpawan** [comment]
Thanks. It's working.
