### ISSUE TITLE
consul health endpoint required by promtheus v2.17.0

### ISSUE THREAD

**Issue by rmie** [twinformatics/eureka-consul-adapter#24]
The following commit to prometheus
https://github.com/prometheus/prometheus/commit/9b9c58aea8e0043bb944961fb776b48ac602c7f9
looks like prometheus is now querying service health endpoint (/v1/health/service/...) which isn't implemented by eureka-consul-adapter.

V2.16.0 seems to be the last prometheus release that is working as of now.

**Comment by tine2k** [comment]
Thanks for the report. I will look into it.
