### ISSUE TITLE
Error refreshing service 

### ISSUE THREAD

**Issue by satworkz** [twinformatics/eureka-consul-adapter#26]
Hi. Thanks it works perfectly fine, except I am getting this error in prometheus logs,

level=error ts=2020-05-07T04:58:40.627Z caller=consul.go:487 component="discovery manager scrape" discovery=consul msg="Error refreshing service" service=TL-GRAPHQL-SERVICE tags= err="Unexpected response code: 503 ({\"timestamp\":\"2020-05-07T04:58:40.625+0000\",\"status\":503,\"error\":\"Service Unavailable\",\"message\":\"No message available\",\"path\":\"/v1/health/service/TL-GRAPHQL-SERVICE\"})"

here is the response from eureka server. Can you please help?

http://XX.XXX.XXX.XXX:8761/v1/health/service/TL-GRAPHQL-SERVICE
[
  {
    "Node": {
      "Node": "TL-GRAPHQL-SERVICE",
      "Address": "XX.XXX.XXX.191",
      "Meta": {}
    },
    "Service": {
      "ID": "XX.XXX.XXX:tl-graphql-service:0",
      "Service": "TL-GRAPHQL-SERVICE",
      "Tags": [],
      "Address": "XX.XXX.XXX.191",
      "Meta": {},
      "Port": 36126
    },
    "Checks": [
      {
        "Node": "TL-GRAPHQL-SERVICE",
        "CheckID": "service:XX.XXX.XXX:tl-graphql-service:0",
        "Name": "Service 'XX.XXX.XXX:tl-graphql-service:0' check",
        "Status": "UP"
      }
    ]
  },
  {
    "Node": {
      "Node": "TL-GRAPHQL-SERVICE",
      "Address": "XX.XXX.XXX.192",
      "Meta": {}
    },
    "Service": {
      "ID": "XX.XXX.XXX:tl-graphql-service:0",
      "Service": "TL-GRAPHQL-SERVICE",
      "Tags": [],
      "Address": "XX.XXX.XXX.192",
      "Meta": {},
      "Port": 45759
    },
    "Checks": [
      {
        "Node": "TL-GRAPHQL-SERVICE",
        "CheckID": "service:XX.XXX.XXX:tl-graphql-service:0",
        "Name": "Service 'XX.XXX.XXX:tl-graphql-service:0' check",
        "Status": "UP"
      }
    ]
  }
]

**Comment by tine2k** [comment]
have you set the timeout properly (see readme)?

**Comment by satworkz** [comment]
sorry I missed that. Thank you so much. It's working now.
