### ISSUE TITLE
spring.mvc.async.request-timeout time out should be more than 120s

### ISSUE THREAD

**Issue by rmie** [twinformatics/eureka-consul-adapter#30]
Not sure why and since when, but latest prometheus is using "...&wait=120000ms" instead of 30000ms. The recommended 
setting for spring.mvc.async.request-timeout is therefor too low.

e.g: http://myhost:8761/v1/health/service/myservice?index=1607944730158&stale=&wait=120000ms"

**Comment by Subrhamanya** [comment]
Is this project still maintained?

**Comment by rmie** [comment]
I'm not the project owner, but

> This project contains a Spring Boot Starter that registers HTTP endpoints on a [Spring Cloud Eureka server](https://cloud.spring.io/spring-cloud-netflix/) to support [Prometheus](https://prometheus.io/)'s [discovery mechanism for Consul (<consul_sd_config>)](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cconsul_sd_config%3E)

Prometheus got native support for eureka service discovery a few years ago:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#eureka_sd_config

So I guess this project has no purpose anymore.
